use_frameworks!

target 'TFCircleProgress_Example' do
  pod 'TFCircleProgress', :path => '../'
  pod 'SnapKit'

  target 'TFCircleProgress_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
